### PR TITLE
./rust code update and ./dss/raft description update

### PR DESCRIPTION
**Pull request by HunDunDM**
* Practical Networked Applications in Rust
  * Update: `BufReaderWithPos` ~~and `BufWriterWithPos`~~.
  * Fix: `Temp_dir` is dropped during the test.
* Distributed Systems in Rust
  * Update: README.md
  * Fix: wrong code in the comment.

### CODE REVIEW

**Comment by overvenus** [comment]
PTAL @sticnarf

**Comment by HunDunDM** [comment]
> Thanks! But I think when creating `BufWriterWithPos` and `BufReaderWithPos`, it shoudn't have extra semantics about where its cursor should be. `SeekFrom::Current(0)` is just to update the internal pos to be the same as the actual one.
> The rest LGTM.

I agree. So can I think that the return value of `seek(SeekFrom::End(0))` is inconsistent with expectations?

**Comment by sticnarf** [comment]
> > Thanks! But I think when creating `BufWriterWithPos` and `BufReaderWithPos`, it shoudn't have extra semantics about where its cursor should be. `SeekFrom::Current(0)` is just to update the internal pos to be the same as the actual one.
> > The rest LGTM.
> 
> I agree. So can I think that the return value of `seek(SeekFrom::Current(0))` is inconsistent with expectations?

Why? The  return value of `seek(SeekFrom::Current(0))`is right the current position of the stream.

**Comment by HunDunDM** [comment]
> Why? The return value of `seek(SeekFrom::Current(0))`is right the current position of the stream.

```rust
use std::fs;
use std::io::{BufWriter, Seek, SeekFrom, Write};
fn main() {
    let fs = fs::OpenOptions::new()
        .write(true)
        .append(true)
        .open("./temp")
        .unwrap(); // Non-empty file, assuming 5 bytes
    let mut buf = BufWriter::new(fs);
    let pos1 = buf.seek(SeekFrom::Current(0)).unwrap();
    let empty_slice = vec![126];
    buf.write(&empty_slice).unwrap();
    buf.flush().unwrap();
    let pos2 = buf.seek(SeekFrom::Current(0)).unwrap();
    println!("first pos: {}, next pos: {}.", pos1, pos2);
    // output: first pos: 0, next pos: 6.
}
```

In the implementation of my homework, I specified it externally. I set `pos` to `seek(SeekFrom::End(0))` for `File` and `0` for `TcpStream`.

```rust
impl<W: Write> BufWriterWithPos<W> {
    pub fn new(inner: W, pos: u64) -> Self {
        Self {
            writer: BufWriter::new(inner),
            pos,
        }
    }
}
```

**Comment by sticnarf** [comment]
@HunDunDM I see. It's just implementation related. The reference implementation doesn't write to an existing file with content, so the position is always right. If I need to append to an existing file with content, I should seek manually to the end of the file then the position is correct. I think it's incorrect to seek to the end when initializing `BufWriterWithPos` because `BufWriterWithPos` should know nothing about the open mode.

**Comment by HunDunDM** [comment]
@sticnarf You are right, it should be sought to the end before `BufWriterWithPos::new`.

I rolled back the relevant code.

**Pull request merged**
