### PR TITLE
rust/docs: change `sytems` to `systems` to fix a typo

### PR DESCRIPTION
**Pull request by fser**
Corrects the link to the github "rust-three-days-course" project.

### CODE REVIEW

**Comment by zz-jason** [comment]
Hi @fser, thanks for your contribution! Please sign the CLA so that we can merge this PR 😄

**Comment by fser** [comment]
Sorry it took me ages to reply. I have made this patch through the github UI. I've just edit the commit to add the "signature", and forced push, but it doesn't look like something changed.

**Comment by fser** [comment]
And also rebased on master.

**Comment by brson** [comment]
Thanks @fser !

**Pull request merged**
