### PR TITLE
rust: remove example solution

### PR DESCRIPTION
**Pull request by sticnarf**
Recently, I find there are some students who turn to the example solution directly before they finish their own project. So I think we need to remove the example solution from the repo.

Note that it does not mean we don't trust students. Probably, they just don't read the lesson plan carefully and click into the solution by mistake.

There is another important reason why we'd better remove it. The distributed system course in this repo adapts the way of filling the framework. It is better to keep consistent among courses. (There is a student who took dss course first. Then, he thought the rust course is the same way so he cloned the repo and modified the existsing code to finish the course.)

### CODE REVIEW

**Comment by balta2ar** [comment]
I'm not a student, just a random guy on the Internet, but I think this change is detrimental to the quality of the course. This course is made open and available to everyone, not just students, by removing the example implementation you take away one of the opportunities to learn for those who are not that lucky to have teachers who they can ask question to. I haven't started the course just yet, I'm yet to go through it, but when I glimpsed over it, the fact that there were example solutions was only in favor of taking this course as a self-study exercise.

**Comment by sticnarf** [comment]
@balta2ar Thanks for letting us know that an example solution makes the course more attractive. But the example solution is actually not part of the course and not an exemplary one quite suitable for self-study.

You can ask any problem in the #rust-training channel on the [TiKV Slack](https://join.slack.com/t/tikv-wg/shared_invite/enQtNTUyODE4ODU2MzI0LTgzZDQ3NzZlNDkzMGIyYjU1MTA0NzIwMjFjODFiZjA0YjFmYmQyOTZiNzNkNzg1N2U1MDdlZTIxNTU5NWNhNjk). In fact, you can still check the history commit for the solution then.

**Comment by liufuyang** [comment]
I somehow feel the same with @balta2ar , removing the solution might make the course much less valuable... 🤔

**Comment by sticnarf** [comment]
OK. As many people are opposed to this change, I decide to close this PR. Reopen it if we think it's necessary in the future.

**Pull request closed without merging**
