### PR TITLE
rust/docs: correct link for rust-three-day-course

### PR DESCRIPTION
**Pull request by mfrw**
Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

### CODE REVIEW

**Comment by zz-jason** [comment]
@mfrw Hi, this PR is conflicted with the master branch, could you pull the latest code and resolve the conflict if free?

**Comment by mfrw** [comment]
@zz-jason I rebased with the new master.

**Comment by brson** [comment]
There's still a problem with the commit history here. GitHub shouldn't be listing a bunch of other people's commits. If a simple rebase doesn't fix it then maybe resetting to origin/master and cherry-picking your commit will.

**Comment by mfrw** [comment]
I am not really an expert, I did a simple rebase with origin/master and pushed the branch.

**Comment by brson** [comment]
I've rebased and pushed to your branch. In the meantime, the "ferrous-systems" change was made in another PR, so this history ended up with only the other commit.

**Comment by brson** [comment]
Thanks @mfrw !

**Pull request merged**
