### PR TITLE
rust(project-3): add git action info and example

### PR DESCRIPTION
**Pull request by Rustin-Liu**
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>

### CODE REVIEW

**Comment by Rustin-Liu** [comment]
Hi @sticnarf, PTAL. I think git action is a good way to do the bench test.  Maybe we can add this info.

**Comment by sticnarf** [comment]
I think it's a good idea to let students try platforms like GitHub Actions. But I'm afraid it may not be a good idea to use it for benchmark. The performance of the instances running github actions can be unstable too.

**Comment by sticnarf** [comment]
What's your opinion? @brson

**Comment by Rustin-Liu** [comment]
It's not a good idea.

**Pull request closed without merging**
